apiVersion: batch/v1
kind: Job
metadata:
  name: migrationjob
  labels:
    app: assignment3-migrations_job
spec:
   template:
     spec:
      containers:
        - name: migrationjob
          image: nyuappsec/assign3:v0
          command: ["python3", "manage.py", "migrate"]
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
               secretKeyRef:
                   name: securing-secrets-part1
                   key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DB
              value: GiftcardSiteDB

            - name: MYSQL_HOST
              value: mysql-service

            - name: ALLOWED_HOSTS
              value: "*,"
                    
            - name: ADMIN_UNAME
              valueFrom:
                secretKeyRef:
                    name: admin-login-secrets
                    key: username

            - name: ADMIN_PASS
              valueFrom:
                secretKeyRef:
                    name: admin-login-secrets
                    key: password
                    
            - name: secret-key
              valueFrom:
                secretKeyRef:
                    name: admin-login-secrets
                    key: secret-key
                    
      restartPolicy: Never
                    
                    
                    
